version: '3.7'
services:
  example_db5:
    container_name: 'example_db5'
    restart: always
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
